py_version: "3.10.14"
go_version: "1.21.0"

jython_version: "2.7.2"
jython_path: "/opt/jython"
jython_bin: "/opt/jython/bin"
jython_exe: "/opt/jython/bin/jython"


docker_dirs:
  - /data/docker
  - /etc/docker

debian_packages_to_remove:
  - docker.io
  - docker-doc
  - docker-compose
  - podman-docker
  - containerd
  - runc
  - docker
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-ce-rootless-extras
  - docker-compose-plugin

debian_packages_to_install:
  - curl
  - git-core
  - gcc
  - make
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - vim
  - libffi-dev
  - lzma
  - liblzma-dev
  - libbz2-dev
  - ca-certificates

debian_docker_packages_to_install:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
