---
- name: "Downloading Golang {{ go_version }}"
  get_url:
    url: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"

- name: "Untaring go files"
  shell: "tar -C /usr/local -xzf /tmp/go{{ go_version }}.linux-amd64.tar.gz"

- name: "Removing downloaded golang.tar.gz"
  file:
    path: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    state: absent

- name: "Update PATH variable for Golang"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=/usr/local/go/bin:${{ ansible_env.PATH}}"
    insertafter: EOF
    create: yes
    state: present
