---
- name: "Append pyenv init script to ~/.profile"
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      ## pyenv configs
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"

      if command -v pyenv 1>/dev/null 2>&1; then
      eval "$(pyenv init -)"
      fi

- name: "Cloning pyenv repo"
  shell: "git clone https://github.com/pyenv/pyenv.git {{ ansible_env.HOME }}/.pyenv"

- name: "Installing Python version {{ py_version }}"
  shell: "source {{ ansible_env.HOME }}/.bashrc && pyenv install {{ py_version }}"
  args:
    executable: /bin/bash

- name: "Configuring Git username/email"
  shell: "git config --global user.email localhost@couchbase.com && git config --global user.name \"Executor\""

- name: "Installing Python packages"
  shell: "source {{ ansible_env.HOME }}/.bashrc && pyenv local {{ py_version }} && curl https://raw.githubusercontent.com/couchbaselabs/TAF/master_py3_dev/requirements.txt | grep -v \"#\" | xargs pip install"
  args:
    executable: /bin/bash
