---
- name: "Cleaning up old docker packages"
  shell: "apt-get remove -y {{ debian_packages_to_remove | join(' ') }}"
  ignore_errors: true

- name: "Create docker data dir"
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ docker_dirs }}"

- name: "Updating docker_deamon.json"
  shell: 'echo "{" > /etc/docker/daemon.json && echo "  \"data-root\": \"/data/docker\"" >> /etc/docker/daemon.json && echo "}" >> /etc/docker/daemon.json'

- name: "Installing key_rings"
  shell: "install -m 0755 -d /etc/apt/keyrings"

- name: "Fetching deb::docker gpg"
  shell: "curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && chmod a+r /etc/apt/keyrings/docker.asc"

- name: "Updating apt-sources for docker"
  shell: "echo \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable\" | tee /etc/apt/sources.list.d/docker.list > /dev/null"

- name: "Update apt"
  shell: "apt-get update"

- name: "Installing docker packages"
  shell: "apt-get install -y {{ debian_docker_packages_to_install | join(' ') }}"

- name: "Fetching docker-compose"
  shell: "curl -L \"https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose"

- name: "Moving docker-compose to /use/bin"
  shell: "mv /usr/local/bin/docker-compose /usr/bin/docker-compose && chmod +x /usr/bin/docker-compose"
